yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list')
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls)
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL
    )

yatube/posts/views.py
from django.shortcuts import get_object_or_404, render

from .models import Group, Post


def index(request):
    title = 'Yatube'
    posts = Post.objects.order_by('-pub_date')[:20]
    context = {
        'posts': posts,
        'title': title
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    title = Group.objects.filter(slug=slug)[0]
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    context = {
        'group': group,
        'posts': posts,
        'title': title
    }
    return render(request, 'posts/group_list.html', context)

yatube/templates/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  </head>
  <title>{% block title %}{{ title }}{% endblock %}</title>
  {% include 'includes/header.html' %}
  {% block content %}
  Блок контента не загрузился
  {% endblock %}
  {% include 'includes/footer.html' %}
</html>

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© 2022 Copyright <span style="color:red">Ya</span>tube</p>    
</footer>

yatube/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
    <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
    <span style="color:red">Ya</span>tube
    </a>
  </div>
</nav>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block content %}
  <h4>Записи группы {{ group.title}}</h4>
    <article>
      <p>{{ group.description }}</p>
      {% for post in posts %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"D E Y" }}
          </li>
        </ul>
      <p>{{ post.text|linebreaksbr }}</p>
    </article>  
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block content %}
  <h4>Последние обновления на сайте</h4>
    <article>
      {% for post in posts %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"D E Y" }}
          </li>
        </ul>
      <p>{{ post.text|linebreaksbr }}</p>
      {% if post.group %}
      <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы {{ post.group.title }}</a>
      {% endif %}
    </article>
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
{% endblock %}